version: '3.8'

services:
  discord-calendar-sync:
    build: .
    container_name: discord-calendar-sync
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./credentials.json:/app/credentials.json:ro
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "health.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a monitoring stack
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 300 discord-calendar-sync
  #   depends_on:
  #     - discord-calendar-sync